window.CURRICULUM_DATA = {
  grades: ["IGCSE"],
  boards: {
    CIE: {
      "IGCSE Chemistry": ["MCQ"],
      "IGCSE Co-ordinated Sciences": ["MCQ"],
    },
  },
};

window.QUESTION_BANK = [
  {
    id: "CIE-MATH-P1-001",
    board: "CIE",
    subject: "Mathematics",
    paper: "P1",
    difficulty: "基础",
    topic: "Functions",
    stem: "Given f(x)=2x+3, find f^{-1}(x).",
    options: ["(x-3)/2", "(x+3)/2", "2x-3", "1/(2x+3)"],
    answer: 0,
    mistakeType: "concept",
    templateId: "fn-inverse-linear",
    skills: ["inverse-functions", "algebra-rearrangement"],
    hints: [
      "令 y=2x+3，然后交换 x 与 y。",
      "把 x=2y+3 变形成 y=...。",
    ],
  },
  {
    id: "CIE-MATH-P1-002",
    board: "CIE",
    subject: "Mathematics",
    paper: "P1",
    difficulty: "中等",
    topic: "Trigonometry",
    stem: "Solve 2sin(x)=1 for 0<=x<360 degrees.",
    options: ["30, 150", "45, 135", "60, 120", "0, 180"],
    answer: 0,
    mistakeType: "calculation",
    templateId: "trig-basic-angles",
    skills: ["trig-equations", "unit-circle"],
    hints: [
      "先化为 sin(x)=1/2，回忆特殊角。",
      "在 0<=x<360 内找正弦为正的解。",
    ],
  },
  {
    id: "CIE-MATH-P2-001",
    board: "CIE",
    subject: "Mathematics",
    paper: "P2",
    difficulty: "冲刺",
    topic: "Differentiation",
    stem: "Find the stationary points of y=x^3-3x^2-9x+1.",
    options: ["x=-1,3", "x=1,-3", "x=0,3", "x=-1,-3"],
    answer: 0,
    mistakeType: "question_reading",
    templateId: "stationary-points-cubic",
    skills: ["differentiation", "stationary-points"],
    hints: [
      "先对函数求导。",
      "令导数为 0，解出驻点横坐标。",
    ],
  },
  {
    id: "CIE-MATH-P3-001",
    board: "CIE",
    subject: "Mathematics",
    paper: "P3",
    difficulty: "中等",
    topic: "Integration",
    stem: "Evaluate integral of (3x^2+2x) dx from 1 to 3.",
    options: ["32", "30", "26", "24"],
    answer: 0,
    mistakeType: "calculation",
    templateId: "definite-integral-polynomial",
    skills: ["integration", "definite-integral"],
    hints: [
      "先逐项求原函数。",
      "再做上限减下限。",
    ],
  },
  {
    id: "CIE-MATH-P4-001",
    board: "CIE",
    subject: "Mathematics",
    paper: "P4",
    difficulty: "冲刺",
    topic: "Vectors",
    stem: "Find the angle between vectors a and b.",
    options: ["Use cos(theta)=a.b/|a||b|", "Use sin(theta)=a+b", "Use |a-b| only", "Cannot be found"],
    answer: 0,
    mistakeType: "concept",
    templateId: "vector-angle-formula",
    skills: ["vectors", "dot-product"],
    hints: [
      "向量夹角用点积公式。",
      "cos(theta)=(a.b)/(|a||b|)。",
    ],
  },
  {
    id: "CIE-PHY-AS-001",
    board: "CIE",
    subject: "Physics",
    paper: "AS Core",
    difficulty: "基础",
    topic: "Kinematics",
    stem: "A car accelerates uniformly from rest. Calculate final speed after 5s at 2m/s^2.",
    options: ["10 m/s", "7 m/s", "2.5 m/s", "5 m/s"],
    answer: 0,
    mistakeType: "calculation",
    templateId: "kinematics-uv-at",
    skills: ["kinematics", "equations-of-motion"],
    hints: [
      "优先使用 v=u+at。",
      "代入 u=0,a=2,t=5。",
    ],
  },
  {
    id: "CIE-MATH-P1-003",
    board: "CIE",
    subject: "Mathematics",
    paper: "P1",
    difficulty: "基础",
    topic: "Algebra",
    stem: "Expand (x+2)(x-5).",
    options: ["x^2-3x-10", "x^2+3x-10", "x^2-10", "x^2-7x+10"],
    answer: 0,
    mistakeType: "calculation",
    templateId: "algebra-expand-binomial",
    skills: ["algebra", "expansion"],
    hints: [
      "括号展开时逐项相乘。",
      "最后合并同类项。",
    ],
  },
  {
    id: "CIE-MATH-P2-002",
    board: "CIE",
    subject: "Mathematics",
    paper: "P2",
    difficulty: "中等",
    topic: "Logarithms",
    stem: "If log2(x)=5, then x equals?",
    options: ["32", "25", "10", "64"],
    answer: 0,
    mistakeType: "concept",
    templateId: "logarithm-to-exponential",
    skills: ["logarithms", "indices"],
    hints: [
      "把 log 形式改写为指数形式。",
      "2 的 5 次方是多少？",
    ],
  },
  {
    id: "CIE-MATH-P3-002",
    board: "CIE",
    subject: "Mathematics",
    paper: "P3",
    difficulty: "冲刺",
    topic: "Probability",
    stem: "For independent events A and B, P(A∩B) equals?",
    options: ["P(A)P(B)", "P(A)+P(B)", "P(A)-P(B)", "1-P(A)"],
    answer: 0,
    mistakeType: "concept",
    templateId: "probability-independent-events",
    skills: ["probability", "independence"],
    hints: [
      "独立事件交集用乘法。",
      "套用 P(A∩B)=P(A)P(B)。",
    ],
  },
  {
    id: "CIE-IGCHEM-MCQ-001",
    board: "CIE",
    subject: "IGCSE Chemistry",
    paper: "MCQ",
    difficulty: "基础",
    topic: "Atomic Structure",
    stem: "Which statement about isotopes is correct?",
    options: [
      "They have the same proton number but different nucleon numbers",
      "They have the same nucleon number but different proton numbers",
      "They have different proton numbers and different electron numbers",
      "They are atoms of different elements with the same mass",
    ],
    answer: 0,
    mistakeType: "concept",
    templateId: "igchem-isotopes",
    skills: ["atomic-structure", "definitions"],
    hints: [
      "同位素属于同一种元素。",
      "同一种元素意味着质子数相同。",
    ],
  },
  {
    id: "CIE-IGCHEM-MCQ-002",
    board: "CIE",
    subject: "IGCSE Chemistry",
    paper: "MCQ",
    difficulty: "中等",
    topic: "Chemical Bonding",
    stem: "What type of bonding is present in magnesium oxide, MgO?",
    options: ["Ionic bonding", "Covalent bonding", "Metallic bonding", "Hydrogen bonding"],
    answer: 0,
    mistakeType: "concept",
    templateId: "igchem-bonding-mgo",
    skills: ["bonding", "ions"],
    hints: [
      "Magnesium forms Mg2+ and oxygen forms O2-.",
      "Attraction between oppositely charged ions is ionic bonding.",
    ],
  },
  {
    id: "CIE-IGCHEM-MCQ-003",
    board: "CIE",
    subject: "IGCSE Chemistry",
    paper: "MCQ",
    difficulty: "基础",
    topic: "Stoichiometry",
    stem: "What is the relative formula mass (Mr) of CO2? (C=12, O=16)",
    options: ["44", "28", "32", "16"],
    answer: 0,
    mistakeType: "calculation",
    templateId: "igchem-mr-co2",
    skills: ["stoichiometry", "relative-formula-mass"],
    hints: [
      "先把化学式里每种原子的相对原子质量加总。",
      "CO2 含 1 个 C 和 2 个 O。",
    ],
  },
  {
    id: "CIE-IGCHEM-MCQ-004",
    board: "CIE",
    subject: "IGCSE Chemistry",
    paper: "MCQ",
    difficulty: "中等",
    topic: "Rates of Reaction",
    stem: "Which change increases the rate of reaction between marble chips and dilute hydrochloric acid?",
    options: [
      "Using smaller marble chips",
      "Lowering the temperature",
      "Using a more dilute acid",
      "Removing the acid after 10 seconds",
    ],
    answer: 0,
    mistakeType: "concept",
    templateId: "igchem-rate-surface-area",
    skills: ["rates", "collision-theory"],
    hints: [
      "反应速率与有效碰撞频率有关。",
      "表面积更大时，单位时间碰撞更多。",
    ],
  },
  {
    id: "CIE-IGCHEM-MCQ-005",
    board: "CIE",
    subject: "IGCSE Chemistry",
    paper: "MCQ",
    difficulty: "冲刺",
    topic: "Acids and Bases",
    stem: "A solution has pH 3. Which statement is correct?",
    options: [
      "It is acidic and has [H+] greater than [OH-]",
      "It is neutral and has [H+] equal to [OH-]",
      "It is alkaline and has [OH-] greater than [H+]",
      "It is alkaline because pH is less than 7",
    ],
    answer: 0,
    mistakeType: "concept",
    templateId: "igchem-ph-interpret",
    skills: ["acids-bases", "ph-scale"],
    hints: [
      "pH 小于 7 表示酸性。",
      "酸性溶液中 [H+] 大于 [OH-]。",
    ],
  },
];

window.SAMPLE_WRONG_LOG = [
  { topic: "Functions", mistake: "concept", correct: 6, wrong: 4 },
  { topic: "Trigonometry", mistake: "calculation", correct: 3, wrong: 7 },
  { topic: "Differentiation", mistake: "question_reading", correct: 4, wrong: 6 },
  { topic: "Integration", mistake: "calculation", correct: 7, wrong: 3 },
];
